<?php
// *** This file is generated by WebsiteBaker Ver.2.8.2
// *** Creation date: 2011-11-09T20:06:57+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	header('HTTP/1.1 301 Moved Permanently');
	header('Location: http://wb282.wdsnet/2.8.x/wb/index.php');
// *************************************************
