<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2012-02-29T23:38:56+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	header('HTTP/1.0 301 Moved Permanently');
	header('Location: http://wb282.wdsnet/2.8.x/wb/index.php');
// *************************************************
