<?php
/**
  Module developed for the Open Source Content Management System Website Baker (http://websitebaker.org)
  Copyright (C) 2008, ISTeam, Werner von der Decken
  Contact me: wkl(at)isteam.de, http://isteam.de

  This module is free software. You can redistribute it and/or modify it
  under the terms of the GNU General Public License  - version 2 or later,
  as published by the Free Software Foundation: http://www.gnu.org/licenses/gpl.html.

  This module is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

 -----------------------------------------------------------------------------------------
  ENGLISH LANGUAGE FILE FOR THE PREFERENCES MODULE
 -----------------------------------------------------------------------------------------
	UPDATE HISTORY:
	Werner von der Decken; 17.05.2008
	 + initial release of the English language file
 -----------------------------------------------------------------------------------------
**/
// array for all language dependen text outputs in the front- and backend
// Note: stick to the naming convention: $MOD_MODULE_DIRECTORY
$MOD_PREFERENCE = array(
	'PLEASE_SELECT' => 'please select',
	'DETAILS_SAVED'	=> 'details successfully saved',
	'SAVE_SETTINGS' => 'save details',
	'SAVE_EMAIL'    => 'save email',
	'SAVE_PASSWORD' => 'save password',
	'SAVE_LANGUAGE' => 'Switch language',
	'SET_PREFERENCES_LANGUAGE' => 'Settings are possible only in your linguistic setting! You first have to change the language and start the settings anew!',
);
$TEXT['USERNAME'] = 'Loginname';
$HEADING['SIGNUP2_CONFIMED_REGISTRATION'] = 'Unlock account';
$HEADING['MESSAGE_WELCOME'] = 'Welcome to unlock of your account';

$HELP['SIGNUP_REMEMBER_PASSWORD'] = '<i>Remember your Loginname and Passwoprd please! You will need it later to complete the activation!</i>';
$HELP['CONFIRM_PASSWORD'] = '<i>Enter your Loginname and Password please to finish the the activation!</i>';

$MESSAGE['ACTIVATED_NEW_USER'] = '<b>Your account is activated. You can logon now.</b>';
$MESSAGE['FAILED_NEW_USER'] = '<b>Invalid access data or activation code is expired!</b>';
$MESSAGE['SIGNUP2_ADMIN_INFO'] = '
A new user was registered.

Loginname: {LOGIN_NAME}
UserId: {LOGIN_ID}
E-Mail: {LOGIN_EMAIL}
IP-Address: {LOGIN_IP}
Signup date: {SIGNUP_DATE}
----------------------------------------
Do NOT answer! This e-mail is autogenerated by WebsiteBaker!

';
$MESSAGE['SIGNUP2_BODY_LOGIN_FORGOT'] = '
Hello {LOGIN_DISPLAY_NAME},

You got this email, because you\'ve requested a new password.

Your new password for {LOGIN_WEBSITE_TITLE} is:

Password: {LOGIN_PASSWORD}

For security reasons change the password as soon as possible please.

with kind regards
----------------------------------------
Do NOT answer! This e-mail is autogenerated by WebsiteBaker!
';
$MESSAGE['SIGNUP2_BODY_LOGIN_INFO'] = '
Hello {LOGIN_DISPLAY_NAME},

Welcome on \'{LOGIN_WEBSITE_TITLE}\'

Your account for  \'{LOGIN_WEBSITE_TITLE}\' is:
Login name: {LOGIN_NAME}
Password: {LOGIN_PASSWORD}

Thank you for registration.
For security reasons change the password as soon as possible please.

';

$MESSAGE['SUCCESS_EMAIL_TEXT_GENERATED'] = "\n"
."***************************************************************************\n"
."This e-mail is autogenerated by WebsiteBaker! Do NOT answer to this e-mail!\n"
."If you got this email by a mistake, please excuse and delete this e-mail.\n"
."***************************************************************************\n";

$MESSAGE['INCORRECT_CAPTCHA'] = 'The given code does not match. If you have problems reading the code, please write an e-mail to the <a href="mailto:{{webmaster_email}}">Webmaster</a>';

$MESSAGE['CONFIRMED']  = 'You can find your password below. Use it to maintain your settings and functions. For security reasons change the password as soon as possible please.';
$MESSAGE['CONFIRMED'] .= 'Password: ';
$MESSAGE['CONFIRMED'] .= 'Thank you!';
$MESSAGE['CHANGE_PASSWORD'] = 'For security reasons change the password as soon as possible please. For that visit following website:';

$MESSAGE['LOGIN_BOTH_BLANK'] = 'Give your login name and password please';
$MESSAGE['LOGIN_PASSWORD_BLANK'] = 'Give your password please';
$MESSAGE['LOGIN_PASSWORD_TOO_LONG'] = 'given password is too long';
$MESSAGE['LOGIN_PASSWORD_TOO_SHORT'] = 'given password is too short';
$MESSAGE['LOGIN_USERNAME_BLANK'] = 'Give your login name please';
$MESSAGE['LOGIN_USERNAME_TOO_LONG'] = 'given login name is too long';
$MESSAGE['LOGIN_USERNAME_TOO_SHORT'] = 'given login name is too short';
$MESSAGE['MAIL_GENERATED'] = 'This email is autogenerated by WebsiteBaker! Do NOT answer to this e-mail! If you need some help or you have any questions, please contact <a href="mailto:{{webmaster_email}}">Webmaster</a>';

$MESSAGE['SEND_CONFIRMED_REGISTRATION'] = "

Hello {LOGIN_DISPLAY_NAME},

welcome on {LOGIN_WEBSITE_TITLE}!

Click the link below to activate your account and finalize your signup:

{LINK}

If the link is not clickable, please copy it into your browser!

This activation link will exceed on {CONFIRMED_REGISTRATION_ENDTIME}

with kind regards,
your Support Team

";
$MESSAGE['SEND_CONFIRMED_ACTIVATION'] = "

Hello {LOGIN_DISPLAY_NAME},

welcome on {LOGIN_WEBSITE_TITLE}!

Your account now is successful activated. You can login now.

If you need some help or you have any questions, please contact the <a href=\"mailto:{{webmaster_email}}\">Webmaster</a>

with kind regards,
your Support Team

";

$MESSAGE['SIGNUP2_SUBJECT_NEW_USER'] = 'Thank you for signing up.';
$MESSAGE['SIGNUP2_NEW_USER'] = 'A new user has signed up';
$MESSAGE['SIGNUP2_SUBJECT_LOGIN_INFO'] = 'Your WB account data ...';
$MESSAGE['SIGNUP_NO_EMAIL'] = 'Please key in your valid email address';

$MESSAGE['SIGNUP_CONFIRMED_REGISTRATION'] = "To be able to use your account, receive during the next minutes e-mail with a link to activate your account.
<br /><b>The activation must be done during 24 hours. Otherwise the account will be deleted.</b>
";
$MESSAGE['SIGNUP_REGISTRATION'] = 'You get your data by e-mail!!';
$MESSAGE['SIGNUP_NEW_USER'] = '<b>Your account is created.</b>';
$MESSAGE['SIGNUP_ACTIVATION'] = 'Account Activation';

$TEXT['NEED_CURRENT_PASSWORD'] = 'confirm with your password please';
$TEXT['NEED_TO_LOGIN'] = 'You need to logon';
$TEXT['NEW_PASSWORD'] = 'New password';
$TEXT['PASSWORD'] = 'Password';
$TEXT['ACTIVATION'] = 'Activate';
$TEXT['SEND'] = 'Request';
$TEXT['USERNAME'] = 'Login name';
$TEXT['INFO'] = '';
